config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'dashboard#index'
  resources :issues
  resources :books
  get 'dashboard/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :student
  belongs_to :room
  belongs_to :book
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    include Pagy::Backend
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books or /books.json
  def index
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true)
   
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to books_path, notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :isbn, :author, :number, :condition)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @pagy, @books = pagy(Book.order(created_at: :desc), items: 5)
    @issues = Issue.all
    @students = Student.all
    @rooms = Room.all
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_issue, only: %i[ show edit update destroy ]

  # GET /issues or /issues.json
  def index
    @q = Issue.ransack(params[:q])
    @issues = @q.result(distinct: true)
  end

  # GET /issues/1 or /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues or /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to issues_path, notice: "Issue was successfully created." }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1 or /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to issues_path, notice: "Issue was successfully updated." }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1 or /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: "Issue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def issue_params
      params.require(:issue).permit(:student_id, :room_id, :book_id, :issuedate, :collectiondate, :status, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/books/_form.html.erb
<section class="main_content dashboard_part large_header_bg">
      
     <!--/ menu  -->
     <div class="main_content_iner overly_inner ">
         <div class="container-fluid p-0 ">
             <!-- page title  -->
             <div class="row">
                 <div class="col-12">
                     <div class="page_title_box d-flex flex-wrap align-items-center justify-content-between">
                         <div class="page_title_left d-flex align-items-center">
                             <h3 class="f_s_25 f_w_700 dark_text mr_30" >Books</h3>
                             <ol class="breadcrumb page_bradcam mb-0">
                                 <li class="breadcrumb-item"><a href="javascript:void(0);">New</a></li>
                             </ol>
                         </div>
                         <div class="page_title_right">
                             
                         </div>
                     </div>
                 </div>
             </div>
             <div class="row ">
                 <div class="col-xl-12 ">
                     <div class="white_card mb_30 card_height_100">
                         <div class="white_card_header">
                             <div class="row align-items-center justify-content-between flex-wrap">
                                 <div class="col-lg-4">
                                     <div class="main-title">
                                         <h3 class="m-0">Add New Book</h3>
                                     </div>
                                 </div>
                                 <div class="col-lg-4 text-right d-flex justify-content-end">
                                
                                 </div>
                                 
                             </div>
                             <%= form_with(model: book) do |form| %>
                              <% if book.errors.any? %>
                                <div id="error_explanation">
                                  <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
                            
                                  <ul>
                                    <% book.errors.each do |error| %>
                                      <li><%= error.full_message %></li>
                                    <% end %>
                                  </ul>
                                </div>
                              <% end %>
                            <div class="row flex-lg-row">
                              <div class="col-lg-3">
                              <div class="field">
                                <label><%= form.label :title %></label>
                                <%= form.text_field :title, class: 'form-control' %>
                              </div>
                            </div>
                            <div class="col-lg-3">
                              <div class="field">
                                <label><%= form.label :isbn %></label>
                                <%= form.text_field :isbn, class: 'form-control' %>
                              </div>
                            </div>
                            <div class="col-lg-3">
                              <div class="field">
                                <label><%= form.label :author %></label>
                                <%= form.text_field :author, class: 'form-control' %>
                              </div>
                            </div>
                            <div class="col-lg-3">
                              <div class="field">
                                <label><%= form.label :number %></label>
                                <%= form.text_field :number, class: 'form-control' %>
                              </div>
                            </div>
                              <div class="field">
                                <label><%= form.label :condition %></label>
                                <%= form.text_field :condition, class: 'form-control' %>
                              </div>
                            
                              <div class="actions">
                                <%= form.submit class: 'btn btn-primary'%>
                                <%= link_to 'Back', books_path, class: 'btn btn-outline-primary' %>
                              </div>
                            <% end %>
                            </div>
                            </div>
                         </div>
                         <div class="white_card_body">
                             <div id="management_bar"></div>
                         </div>
                     </div>
                 </div>
                 </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/books/edit.html.erb
<%= render 'form', book: @book %>

app/views/books/index.html.erb
<section class="main_content dashboard_part large_header_bg"> 
     <!--/ menu  -->
     <div class="main_content_iner overly_inner ">
         <div class="container-fluid p-0 ">
             <!-- page title  -->
             <div class="row">
                 <div class="col-12">
                     <div class="page_title_box d-flex flex-wrap align-items-center justify-content-between">
                         <div class="page_title_left d-flex align-items-center">
                             <h3 class="f_s_25 f_w_700 dark_text mr_30" >Books</h3>
                             <ol class="breadcrumb page_bradcam mb-0">
                                 <li class="breadcrumb-item"><a href="javascript:void(0);">All Records</a></li>
                             </ol>
                         </div>
                         <div class="page_title_right">
                             
                         </div>
                     </div>
                 </div>
             </div>
             <div class="row ">
                 <div class="col-xl-12 ">
                     <div class="white_card mb_30 card_height_100">
                         <div class="white_card_header">
                             <div class="row align-items-center justify-content-between flex-wrap">
                                 <div class="col-lg-4">
                                     <div class="main-title">
                                         <h3 class="m-0"></h3>
                                     </div>
                                 </div>
                                 <div class="col-lg-4 text-right d-flex justify-content-end">
                                 <%= search_form_for @q do |f| %>

                                  <div class="row flex-lg-row">
                                    <div class="col-lg-4">
                                      <%= f.search_field :title_cont, class: 'form-control', placeholder: 'title' %>
                                    </div>
                                    <div class="col-lg-4">
                                      <%= f.search_field :isbn_cont, class: 'form-control', placeholder: 'isbn' %>
                                    </div>
                                    <div class="col-lg-4">
                                      <%= f.submit "Search", class: 'form-control' %>
                                    </div>
                                  </div>
                                <% end %>
                                 </div>
                                 
                             </div>
                             <table class="table">
                              <thead>
                                <tr>
                                  <th><%= sort_link(@q, :title, 'Book title', default_order: :desc) %></th>
                                  <th>Isbn</th>
                                  <th>Author</th>
                                  <th>Number</th>
                                  <th>Condition</th>
                                  <th colspan="3"></th>
                                </tr>
                              </thead>

                              <tbody>
                                <% @books.each do |book| %>
                                  <tr>
                                    <td><%= book.title %></td>
                                    <td><%= book.isbn %></td>
                                    <td><%= book.author %></td>
                                    <td><%= book.number %></td>
                                    <td><%= book.condition %></td>
                                    <td><%= link_to 'Edit book', edit_book_path(book), class: 'btn btn-outline-primary' %></td>
                                    <td><%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
                                  </tr>
                                <% end %>
                              </tbody>
                            </table>
                            <br>

                            <%= link_to 'New Book', new_book_path, class: 'btn btn-primary'%>
                              </div>
                              </div>
                         </div>
                         <div class="white_card_body">
                             <div id="management_bar"></div>
                         </div>
                     </div>
                 </div>
                 </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/books/new.html.erb
<%= render 'form', book: @book %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Number:</strong>
  <%= @book.number %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @book.condition %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/dashboard/index.html.erb
 
     
 

 
 
 <section class="main_content dashboard_part large_header_bg">
      
     <!--/ menu  -->
     <div class="main_content_iner overly_inner ">
         <div class="container-fluid p-0 ">
             <!-- page title  -->
             <div class="row">
                 <div class="col-12">
                     <div class="page_title_box d-flex flex-wrap align-items-center justify-content-between">
                         <div class="page_title_left d-flex align-items-center">
                             <h3 class="f_s_25 f_w_700 dark_text mr_30" >Dashboard</h3>
                             <ol class="breadcrumb page_bradcam mb-0">
                                 <li class="breadcrumb-item"><a href="javascript:void(0);">Home</a></li>
                                 <li class="breadcrumb-item active">Analytic</li>
                             </ol>
                         </div>
                         <div class="page_title_right">
                             <div class="page_date_button d-flex align-items-center"> 
                                
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
             <div class="row ">
                 <div class="col-xl-8 ">
                     <div class="white_card mb_30 card_height_100">
                         <div class="white_card_header">
                             <div class="row align-items-center justify-content-between flex-wrap">
                                 <div class="col-lg-4">
                                     <div class="main-title">
                                         <h3 class="m-0">Recent Books Issued</h3>
                                     </div>
                                 </div>
                                 <div class="col-lg-4 text-right d-flex justify-content-end">
                                
                                 </div>
                                 
                             </div>
                             <table class="table">
                             <tr>
                               <th>Title</th>
                               <th>Author</th>
                               <th>ISBN</th>
                             </tr>
                             <% @books.each do |book| %>
                             <tr>
                               <td><%= book.title %></td>
                               <td><%= book.author %></td>
                               <td><%= book.isbn %></td>
                             </tr>
                             <% end %>
                             
                           </table>
                         </div>
                         <%== pagy_bootstrap_nav(@pagy) %>
                         <div class="white_card_body">
                             <div id="management_bar"></div>
                         </div>
                     </div>
                 </div>
                 <div class="col-xl-4 ">
                     <div class="white_card card_height_100 mb_30 user_crm_wrapper">
                         <div class="row">
                             <div class="col-lg-6">
                                 <div class="single_crm">
                                     <div class="crm_head d-flex align-items-center justify-content-between" >
                                         <div class="thumb">
                                         <i class="fa fa-book"></i>
                                         </div>
                                        
                                     </div>
                                     <div class="crm_body">
                                         <h4><%= @books.all.count %></h4>
                                         <p>Books</p>
                                     </div>
                                 </div>
                             </div>
                             <div class="col-lg-6">
                                 <div class="single_crm ">
                                     <div class="crm_head crm_bg_1 d-flex align-items-center justify-content-between" >
                                         <div class="thumb">
                                         <i class="fa fa-bar-chart"></i>
                                         </div>
                                         
                                     </div>
                                     <div class="crm_body">
                                         <h4><%= @issues.all.count %></h4>
                                         <p>Books Issued</p>
                                     </div>
                                 </div>
                             </div>
                             <div class="col-lg-6">
                                 <div class="single_crm">
                                     <div class="crm_head crm_bg_2 d-flex align-items-center justify-content-between" >
                                         <div class="thumb">
                                         <i class="fa fa-graduation-cap"></i>
                                         </div>
                                        
                                     </div>
                                     <div class="crm_body">
                                         <h4><%= @students.all.count %></h4>
                                         <p>Students</p>
                                     </div>
                                 </div>
                             </div>
                             <div class="col-lg-6">
                                 <div class="single_crm">
                                     <div class="crm_head crm_bg_3 d-flex align-items-center justify-content-between" >
                                         <div class="thumb">
                                         <i class="fa fa-university"></i>
                                         </div>
                                     </div>
                                     <div class="crm_body">
                                         <h4><%= @rooms.all.count %></h4>
                                         <p>Classes</p>
                                     </div>
                                 </div>
                             </div>
                         </div>
                         
                     </div>
                 </div>
                 
         </div>
     </div>
 
     
     </div>
     
     </div>
 </div>
 
 

app/views/issues/edit.html.erb
<%= render 'form', issue: @issue %>

app/views/issues/index.html.erb
<section class="main_content dashboard_part large_header_bg"> 
     <!--/ menu  -->
     <div class="main_content_iner overly_inner ">
         <div class="container-fluid p-0 ">
             <!-- page title  -->
             <div class="row">
                 <div class="col-12">
                     <div class="page_title_box d-flex flex-wrap align-items-center justify-content-between">
                         <div class="page_title_left d-flex align-items-center">
                             <h3 class="f_s_25 f_w_700 dark_text mr_30" >Books</h3>
                             <ol class="breadcrumb page_bradcam mb-0">
                                 <li class="breadcrumb-item"><a href="javascript:void(0);">All Records</a></li>
                             </ol>
                         </div>
                         <div class="page_title_right">
                             
                         </div>
                     </div>
                 </div>
             </div>
             <div class="row ">
                 <div class="col-xl-12 ">
                     <div class="white_card mb_30 card_height_100">
                         <div class="white_card_header">
                             <div class="row align-items-center justify-content-between flex-wrap">
                                 <div class="col-lg-4">
                                     <div class="main-title">
                                         <h3 class="m-0"></h3>
                                     </div>
                                 </div>
                                 <div class="col-lg-4 text-right d-flex justify-content-end">
                                
                                 </div>
                                 
                             </div>
                             <table class="table">
                              <thead>
                              <tr>
                              <th>Student</th>
                              <th>Room</th>
                              <th>Book</th>
                              <th>Issuedate</th>
                              <th>Collectiondate</th>
                              <th>Status</th>
                              <th>Comment</th>
                              <th colspan="3"></th>
                            </tr>
                          </thead>
                        
                          <tbody>
                            <% @issues.each do |issue| %>
                              <tr>
                                <td><%= issue.student.indexnumber %></td>
                                <td><%= issue.room.name %></td>
                                <td><%= issue.book.title %></td>
                                <td><%= issue.issuedate %></td>
                                <td><%= issue.collectiondate %></td>
                                <td><%= issue.status %></td>
                                <td><%= issue.comment %></td>
                                <td><%= link_to 'Edit book', edit_issue_path(issue), class: 'btn btn-outline-primary' %></td>
                                <td><%= link_to 'Delete', issue, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
                              </tr>
                            <% end %>
                          </tbody>
                            <%#== pagy_bootstrap_nav(@pagy) %>
                            <br>

                            <%= link_to 'Issue a book', new_issue_path, class: 'btn btn-primary'%>
                              </div>
                              </div>
                         </div>
                         <div class="white_card_body">
                             <div id="management_bar"></div>
                         </div>
                     </div>
                 </div>
                 </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/issues/new.html.erb
<%= render 'form', issue: @issue %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @issue.student_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @issue.room_id %>
</p>

<p>
  <strong>Book:</strong>
  <%= @issue.book_id %>
</p>

<p>
  <strong>Issuedate:</strong>
  <%= @issue.issuedate %>
</p>

<p>
  <strong>Collectiondate:</strong>
  <%= @issue.collectiondate %>
</p>

<p>
  <strong>Status:</strong>
  <%= @issue.status %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @issue.comment %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/_sidenav.html.erb
 
<!-- sidebar  -->
<nav class="sidebar">
    <div class="logo d-flex justify-content-between">
        <a class="large_logo" href="/"><%= image_tag(image_path('newlogo.png')) %></a>
        <div class="sidebar_close_icon d-lg-none">
            <i class="ti-close"></i>
        </div>
    </div>
    <ul id="sidebar_menu">
        <li class="">
            <a class="has-arrow" aria-expanded="false">
                <div class="nav_icon_small">
                <%= link_to root_path do %>
                  <i class="fa fa-dashboard icons"></i> &nbsp;&nbsp;Dashboard</a>
                  <% end %>
                </div>
              </a>
           
             <%= link_to books_path do %>
              <i class="fa fa-book icons"></i> &nbsp;&nbsp;Books</a>
              <% end %>
              <%= link_to new_book_path do %>
              <i class="fa fa-plus icons"></i> &nbsp;&nbsp;Add Book</a>
              <% end %>
              <%= link_to issues_path do %>
              <i class="fa fa-bar-chart icons"></i> &nbsp;&nbsp;Books Issued</a>
              <% end %>
              <%= link_to new_issue_path do %>
              <i class="fa fa-handshake-o icons"></i> &nbsp;&nbsp;Issue Book</a>
              <% end %>
              <a href="#"class="icon-a"><i class="fa fa-users icons"></i> &nbsp;&nbsp;Magazine</a>
            
        </li>         
</nav>
 <!--/ sidebar  -->

app/views/layouts/_topnav.html.erb
<!-- menu  -->
<div class="container-fluid no-gutters">
    <div class="row">
        <div class="col-lg-12 p-0 ">
            <div class="header_iner d-flex justify-content-between align-items-center" id="header_iner">
                <div class="sidebar_icon d-lg-none">
                    <i class="ti-menu"></i>
                </div>
                <div class="line_icon open_miniSide d-none d-lg-block">
                    <img src="img/line_img.png" alt="">
                </div>
                

                    <div class="profile_info">
                    <%= image_tag(image_path('profile.svg'), class: 'pro-img') %>
                        <div class="profile_info_iner">
                            <div class="profile_author_name">
                                <p>Librarian</p>
                                <h5><%= current_user.user_name %></h5>
                            </div>
                            <div class="profile_info_details">
                                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library Management System</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

  </head>


  <% if user_signed_in? %>
    <body class="crm_body_bg">
    <%= render 'layouts/sidenav' %>
     <%= render 'layouts/topnav' %>
     <% end %>
    <%= yield %>
  </body>
  
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</html>